# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
domain_name: "meusetech"
email_provider_username: "mtechdev01@gmail.com"
email_provider_password: "MeuseTechDev01"

development:
  secret_key_base: 42f30658bd912331758da8ed66f714d07ffd914c733a5672c498488e6c276201b37ad7585fb7c4f7ac3aae7e0aeea02224b0d25dc54388ea0712898870183cf3

test:
  secret_key_base: b6832740bd3d2c8e9ab792c618afbdb2f2f63ef3773130ef1e24886965b1a3130828a0b5b49c75db149b50a192370424883c3738dde8881266729402e65d1a4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 17a27046a1dde8f91b4694ade9f43ba958a1f674f47df5a8992acce28c5bbca25a94c56f9af8bb7d3d8a62a04b9d6826fdfe00ec839cb6b905e3c77a43b3ea33
